version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/data

  web:
    # image: nginx:1.24-alpine
    build: ./infra/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # default.confにSSLの設定も記述しているため不要
      # - ./infra/nginx/ssl.conf:/etc/nginx/conf.d/ssl.conf
    working_dir: /data

  db:
    build: ./infra/mysql
    ports:
      # Sequel AceでのDB接続のため、ホスト側のポート番号を変更
      - "4306:3306"
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: "Asia/Tokyo"

volumes:
  db-store:
